### ISSUE TITLE
HTML 备忘

### ISSUE THREAD

**Issue by xszi** [xszi/blog#16]

**Comment by xszi** [comment]
## 2. Content

```html
    <body>
        <p>我是第一个P</p>
        <p custom-attr="自定义属性" data-name="ppp" data-first-name="张" data-last-name="三">我是第二个P</p>
        <p data-name="xszi" data-first-name="行" data-last-name="书子">我是第三个P</p>
    </body>
```

```css
            p {
                font-size: 24px;
                margin: 50px;
            }

            p::before {
                color: blue;
                margin: 10px;
            }
            p::after{
                color: darkred;
                margin: 10px;
            }

            p:nth-child(1)::before {
                content: "我是before元素";
            }
            p:nth-child(1)::after {
                content: "我是after元素";
            }
            p:nth-child(2)::before {
                content: "(" attr(data-first-name) ", " attr(data-last-name) ")";
            }
            p:nth-child(2)::after {
                content: "( 小名：" attr(data-first-name) ", 自定义属性测试：" attr(data-last-name) ")";
            }
            p:nth-child(3)::before {
                content: "(" attr(data-first-name) ", " attr(data-last-name) ")";
            }
            p:nth-child(3)::after {
                content: "( 小名" attr(data-name) "。)";
            }
```
